
### Use Actor Token on Local API
GET http://localhost:8000
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18ybXFXemREQWc2blEzd2RMODJibEU2WkNTYVoiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3Mjk5NzIyNjIsImlhdCI6MTcyOTk3MjIwMiwiaXNzIjoiaHR0cHM6Ly9uYXR1cmFsLXRpZ2VyLTE2LmNsZXJrLmFjY291bnRzLmRldiIsIm5iZiI6MTcyOTk3MjE5Miwic2lkIjoic2Vzc18ybnpKVTBVWEtsV2JvamlEYTZQbVJDS1JDT08iLCJzdWIiOiJ1c2VyXzJuekpUejdlbzNRdlJHeENzNzFNemEyaXh4ViJ9.cWZUwU_Dx-AD63975jCbpEiv3B5XYgKq3XAZEQ3_ygfwqgMRUjz3krUjt3Ca6n0PfhkUd3flP-VIsfWU7HwFmWkDrXKfXUUTnk_cj6rcoYwkiXfPOjlGyFuMPWKSsGhijOkJRjUGOh9qaScCTVvPg_BxVckrO8ROfGkv4m7RY0fVSj-AAPb-8-zqXmufp11v7gfdKqEoIpUN7M5e6orQvIAbLUaRSB-lqcAvZHe6wqzlTuqvsllRfviQLJ_zpwo-o3UrFcn-fIwKmWLFADkTU1xjxITS0N298slqN154d_twl2GL1CA01r4aPbnG2TUMXbCC7YXqkju4MhIjBeo9eg
Content-Type: application/json
